Repository padma-yoga/padma-yoga-api, pull requests merged in 2020-05, with the labels that each got.

#1 Start api
  .eslintrc.json
  .prettierrc
  jsconfig.json
  package.json
  src/config/database.js
  src/config/server.js
  src/index.js
  src/router/index.js
  yarn.lock
Labels: good first issue

#3 config_enviroments
  .babelrc
  .gitignore
  package-lock.json
  package.json
  src/config/database.js
  src/index.js
  src/router/index.js
  yarn.lock
Labels: good first issue

#5 User model
  .eslintrc.json
  .gitignore
  jsconfig.json
  package-lock.json
  package.json
  src/controllers/userController.js
  src/models/index.js
  src/models/userModel.js
  src/router/index.js
  src/router/routes/apiVersion.js
  src/router/routes/userRoutes.js
  yarn.lock
Labels: enhancement, good first issue

#10 Add codeclimate
  README.md
Labels: chore

#14 Add auth endpoints and register validations
  package.json
  src/controllers/authController.js
  src/controllers/userController.js
  src/models/userModel.js
  src/router/index.js
  src/router/routes/authRoutes.js
  src/router/routes/userRoutes.js
  src/validations/auth.js
Labels: enhancement
